game:
	gcc marble-game.c -o marble-game -lm -g `sdl2-config --libs --cflags` -lGL -lGLU -Wall -Wextra
level_serializer:
	gcc dev_resources/level_serializer.c -o dev_resources/level_serializer
texture_serializer:
	gcc dev_resources/texture_serializer.c -o dev_resources/texture_serializer
