cli:
	gcc checkers-cli.c checkers.c -o checkers-cli -lm -g
cli-windows:
	x86_64-w64-mingw32-gcc checkers-cli.c checkers.c -o checkers-cli -lm -g
gui:
	gcc checkers-gui.c checkers.c -o checkers-gui -lm -lncursesw -D_XOPEN_SOURCE_EXTENDED
